"""Task Run Names.

Demonstrate custom task run naming using templates and callables.

Airflow equivalent: task_id / custom logging for operator identification.
Prefect approach:    task_run_name as a template string or callable on @task.
"""

from typing import Any

from dotenv import load_dotenv
from prefect import flow, task
from prefect.runtime import task_run


def generate_task_name() -> str:
    """Generate a descriptive task run name from runtime parameters.

    Uses prefect.runtime.task_run to access the current task run's
    parameters at runtime.

    Returns:
        A formatted task run name.
    """
    params = task_run.parameters
    region = params.get("region", "unknown")
    batch_id = params.get("batch_id", 0)
    return f"process-{region}-batch-{batch_id}"


@task(task_run_name="fetch-{source}-page-{page}")
def fetch_data(source: str, page: int) -> dict[str, Any]:
    """Fetch data from a source with a templated task run name.

    The task run name will appear as e.g. "fetch-api-page-1" in
    the Prefect UI.

    Args:
        source: The data source identifier.
        page: The page number to fetch.

    Returns:
        A dict with the fetched data summary.
    """
    result = {"source": source, "page": page, "records": page * 10}
    print(f"Fetched {result['records']} records from {source} page {page}")
    return result


@task(task_run_name=generate_task_name)
def process_batch(region: str, batch_id: int) -> str:
    """Process a batch with a callable-generated task run name.

    The task run name is generated by generate_task_name() using
    runtime parameters.

    Args:
        region: The processing region.
        batch_id: The batch identifier.

    Returns:
        A summary of the processed batch.
    """
    msg = f"Processed batch {batch_id} for region {region}"
    print(msg)
    return msg


@flow(name="core_task_run_names", log_prints=True)
def task_run_names_flow() -> None:
    """Demonstrate custom task run names with templates and callables."""
    # Template-based naming
    fetch_data("api", 1)
    fetch_data("api", 2)
    fetch_data("database", 1)

    # Callable-based naming
    process_batch("us-east", 101)
    process_batch("eu-west", 202)


if __name__ == "__main__":
    load_dotenv()
    task_run_names_flow()
