"""Flow Run Names.

Demonstrate custom flow run naming using templates and callables.

Airflow equivalent: Custom DAG run_id / dag_run naming.
Prefect approach:    flow_run_name as template string or callable on @flow.
"""

import datetime

from dotenv import load_dotenv
from prefect import flow, task
from prefect.runtime import flow_run


def generate_flow_name() -> str:
    """Generate a timestamped flow run name.

    Uses prefect.runtime.flow_run to access runtime context.
    Falls back to a timestamp-based name outside runtime.

    Returns:
        A descriptive flow run name.
    """
    params = flow_run.parameters
    ts = datetime.datetime.now(datetime.UTC).strftime("%Y%m%d-%H%M%S")
    if params:
        return f"dynamic-{ts}"
    return f"dynamic-{ts}"


@task
def generate_report(env: str, date_str: str) -> str:
    """Generate a report for a given environment and date.

    Args:
        env: The target environment (e.g. "prod", "staging").
        date_str: The report date string.

    Returns:
        A report summary.
    """
    msg = f"Report generated for {env} on {date_str}"
    print(msg)
    return msg


@flow(name="core_template_named", flow_run_name="report-{env}-{date_str}", log_prints=True)
def template_named_flow(env: str = "staging", date_str: str = "2025-01-15") -> str:
    """Flow with a template-based run name.

    The flow run name will appear as e.g. "report-staging-2025-01-15"
    in the Prefect UI.

    Args:
        env: Target environment.
        date_str: Report date.

    Returns:
        The report result.
    """
    return generate_report(env, date_str)


@flow(name="core_callable_named", flow_run_name=generate_flow_name, log_prints=True)
def callable_named_flow() -> str:
    """Flow with a callable-generated run name.

    The flow run name is generated by generate_flow_name() using
    runtime context.

    Returns:
        A confirmation message.
    """
    msg = "callable_named_flow completed"
    print(msg)
    return msg


@flow(name="core_flow_run_names", log_prints=True)
def flow_run_names_flow() -> None:
    """Orchestrate subflows that demonstrate custom run naming."""
    template_named_flow("prod", "2025-06-01")
    callable_named_flow()


if __name__ == "__main__":
    load_dotenv()
    flow_run_names_flow()
