"""Generate root prefect.yaml from flows/ directory.

Scans all Python files under flows/, uses the ast module to find @flow-decorated
functions, identifies the "main" flow per file (the one called inside
``if __name__ == "__main__":``), and writes a prefect.yaml with one deployment
entry per main flow.

Usage:
    uv run python scripts/generate_prefect_yaml.py
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FLOWS_DIR = ROOT / "flows"
OUTPUT = ROOT / "prefect.yaml"


def find_flow_functions(tree: ast.Module) -> dict[str, str | None]:
    """Return a mapping of function_name -> flow name kwarg for @flow-decorated functions."""
    flows: dict[str, str | None] = {}
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for decorator in node.decorator_list:
            is_flow = False
            flow_name: str | None = None
            if isinstance(decorator, ast.Name) and decorator.id == "flow":
                is_flow = True
            elif isinstance(decorator, ast.Call):
                func = decorator.func
                if isinstance(func, ast.Name) and func.id == "flow":
                    is_flow = True
                    for kw in decorator.keywords:
                        if kw.arg == "name" and isinstance(kw.value, ast.Constant):
                            flow_name = kw.value.value
            if is_flow:
                flows[node.name] = flow_name
    return flows


def find_main_call(tree: ast.Module) -> str | None:
    """Find the function called inside ``if __name__ == "__main__":``."""
    for node in ast.iter_child_nodes(tree):
        if not isinstance(node, ast.If):
            continue
        # Match: if __name__ == "__main__"
        test = node.test
        if not isinstance(test, ast.Compare):
            continue
        if not (
            isinstance(test.left, ast.Name)
            and test.left.id == "__name__"
            and len(test.ops) == 1
            and isinstance(test.ops[0], ast.Eq)
            and len(test.comparators) == 1
            and isinstance(test.comparators[0], ast.Constant)
            and test.comparators[0].value == "__main__"
        ):
            continue
        # Find the first function call in the body
        for stmt in node.body:
            if isinstance(stmt, ast.Expr) and isinstance(stmt.value, ast.Call):
                call = stmt.value
                if isinstance(call.func, ast.Name):
                    return call.func.id
                if isinstance(call.func, ast.Attribute):
                    return call.func.attr
    return None


def scan_flows() -> list[dict[str, str]]:
    """Scan flows/ and return a sorted list of deployment entries."""
    entries: list[dict[str, str]] = []

    for py_file in sorted(FLOWS_DIR.rglob("*.py")):
        if py_file.name.startswith("_"):
            continue
        source = py_file.read_text(encoding="utf-8")
        try:
            tree = ast.parse(source, filename=str(py_file))
        except SyntaxError:
            print(f"WARNING: skipping {py_file} (syntax error)", file=sys.stderr)
            continue

        flows = find_flow_functions(tree)
        if not flows:
            continue

        main_func = find_main_call(tree)
        if main_func is None or main_func not in flows:
            # Fall back: if there is exactly one flow, use it
            if len(flows) == 1:
                main_func = next(iter(flows))
            else:
                continue

        flow_name = flows[main_func] or main_func
        entrypoint = f"{py_file.relative_to(ROOT)}:{main_func}"
        deploy_name = flow_name.replace("_", "-")

        entries.append(
            {
                "name": deploy_name,
                "entrypoint": entrypoint,
                "flow_name": flow_name,
            }
        )

    return entries


def generate_yaml(entries: list[dict[str, str]]) -> str:
    """Build the prefect.yaml content string."""
    lines: list[str] = []
    lines.append("# Auto-generated by scripts/generate_prefect_yaml.py")
    lines.append("# Regenerate with: make generate-prefect-yaml")
    lines.append("")
    lines.append("pull:")
    lines.append("  - prefect.deployments.steps.set_working_directory:")
    lines.append("      directory: .")
    lines.append("")
    lines.append("deployments:")

    for entry in entries:
        lines.append(f"  - name: {entry['name']}")
        lines.append(f"    entrypoint: {entry['entrypoint']}")
        lines.append("    work_pool:")
        lines.append("      name: default")
        lines.append("    schedules: []")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    entries = scan_flows()
    yaml_content = generate_yaml(entries)
    OUTPUT.write_text(yaml_content, encoding="utf-8")
    print(f"Generated {OUTPUT} with {len(entries)} deployments")


if __name__ == "__main__":
    main()
